#!/bin/bash

alias ls='ls --color=auto'
alias dir='dir -G'
alias vdir='vdir -G'

alias grep='grep -G'
alias fgrep='fgrep -G'
alias egrep='egrep -G'

alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias emacs-cn='LC_ALL=zh_CN.UTF-8 emacs'

alias rsync='rsync -avz --progress'

alias checkstyle='java -jar /opt/checkstyle/checkstyle-5.5-all.jar -c /opt/checkstyle/checkstyle.xml'
alias findbugs='findbugs -textui -include /opt/findbugs/findbugs.xml'

alias mountcd='sudo mount /dev/sr0'

alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

# Pacman alias examples
 alias pacupg='sudo pacman -Syu'        # Synchronize with repositories before upgrading packages that are out of date on the local system.
 alias pacin='sudo pacman -S'           # Install specific package(s) from the repositories
 alias pacins='sudo pacman -U'          # Install specific package not from the repositories but from a file 
 alias pacre='sudo pacman -R'           # Remove the specified package(s), retaining its configuration(s) and required dependencies
 alias pacrem='sudo pacman -Rns'        # Remove the specified package(s), its configuration(s) and unneeded dependencies
 alias pacrep='pacman -Si'              # Display information about a given package in the repositories
 alias pacreps='pacman -Ss'             # Search for package(s) in the repositories
 alias pacloc='pacman -Qi'              # Display information about a given package in the local database
 alias paclocs='pacman -Qs'             # Search for package(s) in the local database

 # Additional pacman alias examples
 alias pacupd='sudo pacman -Sy && sudo abs'     # Update and refresh the local package and ABS databases against repositories
 alias pacinsd='sudo pacman -S --asdeps'        # Install given package(s) as dependencies of another package
 alias pacmir='sudo pacman -Syy'                # Force refresh of all package lists after updating /etc/pacman.d/mirrorlist
 alias pacclean='sudo pacman -Scc'      # clean cache

alias -s txt=vim
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'

alias glggap="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative --decorate --all"
alias gsetup="git config user.name 'Jeoygin'; git config user.email 'jeoygin@gmail.com'"

alias ss1='ssh -t wangrj@access1 ssh'
alias ss2='ssh -t wangrj@access2 ssh'
